# Generated by Django 2.2.1 on 2020-10-30 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20201030_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='pincode',
        ),
    ]
